### ISSUE TITLE
Error on ImportDeclaration

### ISSUE THREAD

**Issue by CMatias** [estools/escope#106]
When running this piece of code:
```
var ast = esprima.parse(fs.readFileSync('test.js'), {sourceType: "module", loc: true, range: true, comment: true});
var scopeManager = escope.analyze(ast);
var currentScope = scopeManager.acquire(ast);   
``` 
on the ast generated by this file:

``` 
import path from "path";
import * as fs from "fs";
```

I get the following:  ImportDeclaration should appear when the mode is ES6 and in the module context

Searching google gets me to this issue https://github.com/eslint/eslint/issues/4344

Not sure if they're related but as it appears to be solved it may only be a dependency problem.

**Comment by RReverser** [comment]
As it says, you need to analyze in ES6 mode and module context:

```javascript
escope.analyze(ast, { ecmaVersion: 6, sourceType: 'module' })
```
