### ISSUE TITLE
Function scope arguments variable

### ISSUE THREAD

**Issue by BuildingJarl** [estools/escope#114]
Function scopes have a variable named arguments in variables array. Could you please explain why?

```
function one() {
}

function two(foo) {
}
```

```
Function one variables array:
variables: Array
    0: Variable
        name: arguments
```

```
Function two variables array:
variables: Array
    0: Variable
        name: arguments
    1: Variable
       name: foo
```

**Comment by michaelficarra** [comment]
JavaScript functions introduce a variable named `arguments` into scope. You can confirm this yourself by reading the language specification.
