### ISSUE TITLE
Use ES6

### ISSUE THREAD

**Issue by Constellation** [estools/escope#40]
Use ES6 to write escope.

One technical note is that, current `jsdoc` doesn't support it...

**Comment by okuryu** [comment]
YUIDoc should works well. :)

**Comment by Constellation** [comment]
@okuryu,

Oh! That sounds great. I'll try it out :)

**Comment by Constellation** [comment]
Seeing the latest jsdoc, we can parse the ES6 :D
So I've updated the code base to ES6.
