### ISSUE TITLE
ScopeManager.prototype.attach doesn't seem to do anything anymore

### ISSUE THREAD

**Issue by kevinb7** [estools/escope#45]
Has ```attach``` been deprecated?  If so, what should I be using instead?

**Comment by Constellation** [comment]
Yes.
Previously it is used to attach scope to Node property. But now, we use WeakMap to maintain this relationship, so `attach` and `detach` is not necessary anymore.

**Comment by Constellation** [comment]
Simply, `acquire(node)` returns the scope :)
(node is the AST node that creates scope, e.g. `FunctionExpression`)

**Comment by kevinb7** [comment]
Thanks.  Would you mind if I add a "Usage" section to README.md that describes this?

**Comment by Constellation** [comment]
That's very very nice!

**Comment by kevinb7** [comment]
Cool.  I'll do that right after I get it working in my code.
