### ISSUE TITLE
Missing super identifier

### ISSUE THREAD

**Issue by nzakas** [estools/escope#50]
In class methods, there should be a `super` identifier prepopulated in the scope (similar to `this` and `arguments`).

**Comment by michaelficarra** [comment]
That isn't how `super` works. It must be the target of a call or a member access. It is not a regular identifier, doesn't resolve how other identifiers do in the scope chain, and shouldn't show up in escope's output.

**Comment by nzakas** [comment]
It needs to show up as a reference somehow to have a complete picture of what's happening. How would you recommend that be done?

**Comment by michaelficarra** [comment]
Since super resolves through home objects, you should be able to statically resolve these references. I'm not sure what you're asking.

**Comment by nzakas** [comment]
Not exactly. I suppose what I'm really asking for is for `super` to act like `this` in escope. `this` doesn't exist as a scope variable and `this` references don't count as references in escope. The problem right now is that `super` does count as a refreshed, and that's throwing things off.

**Comment by michaelficarra** [comment]
Agreed. :+1:

**Comment by Constellation** [comment]
@nzakas:

LGTM. `escope` should handle `super` reference specially.

**Comment by Constellation** [comment]
@nzakas, @michaelficarra :+1: 

How `super` is handled in `estree` project?
We need to align it.

**Comment by nzakas** [comment]
`super` is just represented as an `Identifier`, same as `this`.

**Comment by Constellation** [comment]
I remember that `this` is represented as `ThisExpression`, right?
Anyway, I'll implement it with assumption that `super` is represented as `Identifier`.

**Comment by nzakas** [comment]
Oh yeah, there's `ThisExpression`. So far, there's no `SuperExpression`. I just filed an issue to get clarification: https://github.com/estree/estree/issues/54

**Comment by Constellation** [comment]
@nzakas 
Cool :)
