### ISSUE TITLE
Upgrade major version of escope

### ISSUE THREAD

**Issue by Constellation** [estools/escope#54]
Now `estraverse`, `esrecurse` used in escope are upgraded and there's added/removed AST nodes,
so there're breaking changes. So I think it's time to upgrade major version.

@nzakas 
Is it possible to upgrade the major version of escope on whcih eslint depends?
If it's too difficult, we need to consider another way.

**Comment by nzakas** [comment]
Yup, it's possible.

**Comment by Constellation** [comment]
@nzakas 
Great!!!!!!!! So I'll release it as `3.0.0`. It includes many ES6 node supports,
`RestElement`, `AssignmentElement` (which enables default parameters) etc.

**Comment by nzakas** [comment]
Cool! Does it also support `SuperExpression`?

**Comment by Constellation** [comment]
I've published it as `3.0.0`!

@nzakas:
Partially yes. `SuperExpression` is currently supported as `Identifier`.
When introducing `SuperExpresison` to estree is done, I'll add it ASAP! (also `estraverse` and `esrecurse`).

NOT:
in the latest release, we use `3.0.0 `estraverse` and `esrecurse`. They are more compilant to estree spec.
Major change is

+ `CatchClause` no longer has `handlers` & `guardedHandlers`
+ `Function` doesn't traverse `defaults` and `rest`

**Comment by Constellation** [comment]
Oops, I've miss-spelled, NOT => NOTE.

**Comment by Constellation** [comment]
When you find bugs, please file it :)
I'll fix them.

**Comment by nzakas** [comment]
`SuperExpression` should be merged soon: https://github.com/estree/estree/pull/57

I'll also have to update Espree to use `RestElement` and `AssignmentElement`. Although, shouldn't `AssignmentElement` be `AssignmentPattern`?

**Comment by Constellation** [comment]
@nzakas 

Ah, oops. `AssignmentElement` is typo. `AssignmentPattern` is right, and `AssignmentPattern` is supported.

> SuperExpression should be merged soon: estree/estree#57

Nice! I'll add it to `estraverse` / `esrecurse` / `escope`.

**Comment by Constellation** [comment]
I've added `SuperExpression` to `estraverse` and `esrecurse` and released them as `3.1.0`.

**Comment by nzakas** [comment]
Thanks!

**Comment by Constellation** [comment]
And released escope as `3.0.1` :)
