### ISSUE TITLE
escope@3.0.0 issues

### ISSUE THREAD

**Issue by nzakas** [estools/escope#58]
I've just upgraded to EScope 3.0.0 for ESLint. Here are some issues I've encountered:

- [ ] `npm i escope@latest` still pulls in 1.0.3 instead of 3.0.0, making it hard to know the latest available version
- [ ] Unknown node type Super - The ESTree spec defined `Super` instead of `SuperExpression`

Otherwise, very smooth upgrade!

**Comment by jesstelford** [comment]
Even just a regular `npm install --save escope` gives version 1.0.3. It appears that maybe v1.0.3 was the most recently published version, so npm is confused about which version to pull?

This is a pretty serious mistake as any new installations are getting a quite old version of escope (I was thoroughly confused when trying to use it until I realized the version mismatch).

**Comment by Constellation** [comment]
Hm, now I've published escope as `3.1.0`. But npm.js doesn't show it.
Maybe I missed some configurations...

**Comment by Constellation** [comment]
Hm, I've logged in npm.js. So I've seen the `3.1.0` is released.

**Comment by wolfgang42** [comment]
`npm` is now installing `escope=3.2.0` as expected.
