### ISSUE TITLE
SwitchStatement scope not being returned with acquire()

### ISSUE THREAD

**Issue by nzakas** [estools/escope#63]
I'm not sure if this is a bug or not, but this behavior is unexpected. If you can let me know if it's a bug, I can try to submit a patch.

If I call this in 3.0.0:

```js
var scope = scopeManager.acquire(node);
```

And the `node` is a `SwitchStatement`, `scope` is undefined. However, there actually is a scope of type `"switch"` that I expected to be returned by this.

Is this behavior expected or a bug?

**Comment by nzakas** [comment]
Also verified as present in 3.0.1.

**Comment by nzakas** [comment]
Nevermind, was running in ES5 mode (doh!)

**Comment by Constellation** [comment]
:)
