### ISSUE TITLE
Use native Map and WeakMap when possible

### ISSUE THREAD

**Issue by RReverser** [estools/escope#67]
Current implementation relies on using `es6-map` and `es6-weak-map` unconditionally which sometimes conflicts with other already injected polyfills or native implementations.

Please make those imports conditional (depending on whether `Map` and `WeakMap` already exist in global scope).

**Comment by RReverser** [comment]
Sorry, my bad, I had pretty old version installed from npm cache.

**Comment by Constellation** [comment]
np :)

**Comment by wtgtybhertgeghgtwtg** [comment]
Now that
