### ISSUE TITLE
For customizing referencer logic.

### ISSUE THREAD

**Issue by mysticatea** [estools/escope#74]
I want to customize escope's referencer logic in order to use ES7 features.
However, `PatternVisitor` is not exposed, so I cannot do.

Could escope export that?

**Comment by nzakas** [comment]
Related: #76

**Comment by robcolburn** [comment]
@mysticatea is this also resolved by #78 ?

**Comment by mysticatea** [comment]
@robcolburn The intent of this issue was to export [`PatternVisitor`](https://github.com/mysticatea/escope/blob/cebbcf404f34791ea86a7284f99b556233fa5bc3/src/referencer.js#L31) to be able to customize.
But yes, as #78's result, this is not required for ES7 syntax, so I can close this.
