### ISSUE TITLE
LeftHandSideExpression of Assignment Expression can be a MemberExpression as well.

### ISSUE THREAD

**Issue by skepticfx** [estools/escope#77]
I feel there is a small bug when walking the AST for `AssignmentExpression`, where the `LeftHandSideExpression` can be a `MemberExpression` as well in addition to `Pattern`.

Currently, the code only considers the `Pattern` type: https://github.com/estools/escope/blob/master/src/referencer.js#L460

Hence, a valid `MemberExpression` assignment like, 
```
document.cookie = "key=value";
```
 would not be stored as a proper `WriteExpr` in the Reference object. Rather there would be one referenece for `document` with a Flag of 1(READ).

Such assignment expressions are alteast very common in browser JavaScript code and a fix would be great. I know the code also, references something similar in the comments: https://github.com/estools/escope/blob/master/src/referencer.js#L98

If its considered a bug, any tips on how to fix this would be greatly appreciated, since I can work on a PR.

**Comment by mysticatea** [comment]
This is a not bug. 
Currently, escope does not support property references.

```js
document.cookie = "key=value";
```

In this case, a reading reference of `document` is needed. It's correct. If `document` is `null`, we see a null reference access error.
If there is a writing property reference of `document.cookie` additionally, it's very useful.

However, it probably is a breaking change.

Related: #41

**Comment by skepticfx** [comment]
I see! Thanks for the explanation. Appreciate it!
