### ISSUE TITLE
Add an option to ignore "isStrict" property

### ISSUE THREAD

**Issue by apendua** [estools/escope#81]
Currently the `"use strict"` completely denies implicit globals detection:

https://github.com/estools/escope/blob/master/src/referencer.js#L449

While this probably makes a lot of sense in many scenarios, it also make things difficult when we try to use `escope` to detect all possible instances of implicit globals throughout the corresponding `ast`. Look here for example:

https://github.com/meteor/meteor/issues/5343#issuecomment-146030175

Do you think it would be possible to add an option to alter this behavior?

**Comment by apendua** [comment]
Anyone?

**Comment by michaelficarra** [comment]
I'm not really sure what the ask is here.

**Comment by RReverser** [comment]
I'm closing this for now. `isStrict` is just a flag which is part of the output, escope doesn't alter any behavior depending on it as far as I can tell from the code. If the issue still exists, please reopen it with detailed examples of what you expect / are actually getting.
