### ISSUE TITLE
Content of try block gets a different scope from parent

### ISSUE THREAD

**Issue by wolfgang42** [estools/escope#86]
Given the following JavaScript:
```javascript
var v;
try {
    v = 1;
} catch(e) {}
```
escope thinks that the `v` inside the `try` block is in the global scope:
```javascript
var local_v;
try {
    global_v = 1;
} catch(e) {}
```

I discovered this when I tried to use escope to refactor a try...catch and found that the code broke because the code inside the try was still using the old variable name.

Here is a test case which does not pass:
```coffeescript
expect = require('chai').expect
esprima = require 'esprima'
escope = require '..'

describe 'try', ->
    it 'finds a variable in the parent scope', ->
        ast = esprima.parse """
        var v;
        try {
            v = 1;
        } catch(e) {}
        """

        scopeManager = escope.analyze ast

        globalScope = scopeManager.scopes[0]
        expect(globalScope.type).to.be.equal 'global'
        expect(globalScope.variables).to.have.length 0
        expect(globalScope.references).to.have.length 0
```

I believe this is related to #57 but I'm not certain.

**Comment by wolfgang42** [comment]
#22 also looks related as well.

**Comment by michaelficarra** [comment]
I don't see anything wrong with this.

```coffee
expect(globalScope.variables).to.have.length 1
```

**Comment by wolfgang42** [comment]
The problem is that the identifier `v` is viewed as having two *different* scopes, one inside the `try` and one outside of it. However it's the same `v` in both places.
