### ISSUE TITLE
Errors in eslint with escope 3.2.1

### ISSUE THREAD

**Issue by dtothefp** [estools/escope#88]
Duplicate of https://github.com/eslint/eslint/issues/4481, not sure which repo is more appropriate to post on.

<img width="578" alt="screen shot 2015-11-19 at 4 17 35 pm" src="https://cloud.githubusercontent.com/assets/4656726/11284660/115312ee-8ed9-11e5-9a99-12968f26f071.png">

```js
//login-spec.js
  const {makeGetters, makeActions, Getters, ...store} = loginData;
  const reactor = registerStores(store);
```

```js
//eslint.config.json
{
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "env": {
    "browser": true
  },
  "ecmaFeatures": {
    "arrowFunctions": true,
    "blockBindings": true,
    "experimentalObjectRestSpread": true,
    "generators": true,
    "jsx": true,
    "module": true,
    "modules": true,
    "restParams": true,
    "spread": true
  }
}
```

Turns out the issues is with `escope` if I install 3.2.0 all works as expected or I guess more accurately as before

<img width="1067" alt="screen shot 2015-11-19 at 4 16 18 pm" src="https://cloud.githubusercontent.com/assets/4656726/11284655/077b4426-8ed9-11e5-934d-3bd2b11c8335.png">

**Comment by michaelficarra** [comment]
See my comment over there. We'll add this when it's an actual ECMAScript feature.

**Comment by michaelficarra** [comment]
Re-opening until I can confirm that the given program's scope analysis is correct.

**Comment by thoov** [comment]
I am running into the same issue

**Comment by dtothefp** [comment]
@michaelficarra this just started happening for me today on Travis. Using eslint `1.9.0` had to use Kaleidoscope to diff my node_modules and by chance found the solution. Like I said not sure if if this issue should be here or on the eslint repo just want to cover my bases and get my builds working again.

**Comment by evenchange4** [comment]
+1  escope@3.2.0 all works fine for me.

**Comment by wuct** [comment]
I set escope to v3.2.0 and all works fine

**Comment by Constellation** [comment]
Nice catch! Could you show me AST dump produced by `babel-eslint` parser? It could help us a lot :)

**Comment by Constellation** [comment]
It seems that, `babel-eslint` dumps `SpreadProperty` node, that is not supported by `escope`.
And this `SpreadProperty` is handled by `babel-eslint`. Investigating...

**Comment by Constellation** [comment]
Merged the change and published `escope@3.3.0`.

**Comment by dtothefp** [comment]
@Constellation as far as I can tell this issue is still not resolved with 3.3.0. Made a demo repo here https://github.com/dtothefp/escope-broken. Not sure if I'm doing something wrong?

**Comment by brunops** [comment]
I believe I'm having this problem too. Webpack works fine with `escope@3.2.0` but fails with `escope@3.2.1` or new `3.3.0`

![screen shot 2015-11-23 at 9 45 31 am](https://cloud.githubusercontent.com/assets/1735844/11344561/fe4a05b8-91c6-11e5-994a-b0b268080c77.png)

**Comment by Constellation** [comment]
@dtothefp, @brunops 

This issue is related to how `babel-eslint` works with `eslint`.
See https://github.com/babel/babel-eslint/pull/209.

**Comment by brunops** [comment]
Thanks @Constellation 
It seems like bumping `babel-eslint` from `^3.1.0` to `^4.1.0` did the trick :+1:
