### ISSUE TITLE
RangeError: Maximum call stack size exceeded in v3.2.1

### ISSUE THREAD

**Issue by plievone** [estools/escope#90]
There is a strange situation that started with escope v3.2.1, and only with npm 2, not 3. To reproduce:

```
git clone https://github.com/graphql/graphql-js
npm install
npm run lint
````
Result: `RangeError: Maximum call stack size exceeded at Referencer.Visitor.visitChildren (graphql-js/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:67:48)`

This is due to eslint depending on escope@3.x, and escope depending on both esrecurse and estraverse, just having pumped the estraverse from 3.x to 4.x The strange thing is, that the situation seems to be due to duplicate estraverse: if estraverse@3 or @4 is installed under both escope and esrecurse, the error happens (the situation in escope@3.2.1). If the estraverse under esrecurse is removed, so that it uses parent escope's estraverse, the error disappears. Also if estraverses from both escope and esrecurse are removed, it works due to estraverse being available on parent eslint too. In npm 3 the error doesn't happen, presumably due to it installing most packages to project root.

I don't know if the fix will be in escope, estraverse or esrecurse, but it seems like there is global state somewhere that doesn't like if there are two estraverse modules installed. Escope is the common element here, so decided to post this issue here.

**Comment by plievone** [comment]
escope uses estraverse.Syntax directly and via esrecurse, so those object identity checks could fail there if they are from separate estraverse modules (haven't investigated more). But I suspect a more probable cause might be 'babel-eslint' not finding the estraverse if it is under esrecurse, so patching the wrong estraverse. Will look into it some more. If so, will move this issue to babel-eslint.

**Comment by plievone** [comment]
I could get rid of the error by updating babel-eslint from 4.0.10 to 4.1.5. The file (eslint/node_modules/escope/node_modules/esrecurse/node_modules/estraverse) is still unpatched, but eslint works for me. I filed an issue in babel-eslint (babel/babel-eslint/issues/211), in case the file should be patched. But closing this issue. Feel free to open if you think that using two estraverse module instances in escope (as it is from 3.2.1 onwards) is causing problems.

**Comment by michaelficarra** [comment]
@plievone You are right, the problem exists in how babel-eslint integrates with escope through mutation of estraverse. When multiple consumers of escope assume they can integrate in this way, issues such as this one arise. It's a problematic design. escope should probably have an interface for accepting a custom estraverse or esrecurse, instead of consumers of escope trying to touch things they shouldn't even be aware of.
