### ISSUE TITLE
v3.3.0 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nikogu** [estools/escope#91]
![image](https://cloud.githubusercontent.com/assets/1179603/11363088/96650e0e-92d2-11e5-9a26-cd6efca82d57.png)

v3.2.0 is ok

**Comment by michaelficarra** [comment]
Did you try searching for duplicates?

**Comment by nikogu** [comment]
i transfer issue to eslint ....  https://github.com/eslint/eslint/issues/4534

**Comment by michaelficarra** [comment]
There's duplicates there as well...
