### ISSUE TITLE
Add feature: implied strict mode

### ISSUE THREAD

**Issue by nre** [estools/escope#92]
I would like to add an 'implied strict mode' feature to escope.

JS without a `"use strict";` directive can still be run in strict mode:

* In Node: e.g. `node --use_strict -e "var private;"`
* In browsers: Build tools and module bundlers can add `"use strict";` automatically.

JSHint has an option for `strict: implied` in v2.9. I would like to add this feature to ESLint (eslint/eslint#4832).

Please let me know if you would accept a PR.

**Comment by michaelficarra** [comment]
Why don't you just add the `'use strict'` directive to the AST yourself before passing it to escope?

**Comment by nre** [comment]
[That suggestion](https://github.com/eslint/eslint/issues/4832#issuecomment-168335647) was rejected by @nzakas. He wanted a proper [flag in escope](https://github.com/eslint/eslint/issues/4832#issuecomment-168402119).

**Comment by nzakas** [comment]
We don't want to modify the AST just to change strict mode.

**Comment by michaelficarra** [comment]
I don't think this is something I would want to add to escope. You can easily make a valid AST invalid by adding a strict mode directive, and in the same way you could make a program nonsensical by trying to treat it as strict mode code when it was parsed in sloppy mode.

**Comment by nzakas** [comment]
This is the same problem as using sourceType or ecmaVersion. Any difference between parsing and scope analysis will cause a problem, so it's up to the consumers to manage that. That's better than modifying an AST after it was produced, as that can potentially affect a lot more.

What we are really asking for here is just access to the internal strict mode tracker so it can be changed.

**Comment by nre** [comment]
Passing the same options to the parser and escope (and the risk that someone mightn't pass the same options to both) is only a symptom of the problem, not the cause.

The parser should be saving its info about strict mode (and other things) in the AST, so that escope doesn't have to work it out too. The problem is that they are independently trying to answer some of the same questions.

**Comment by nre** [comment]
@Constellation, do you approve of the proposed 'implied strict mode' feature?

**Comment by nre** [comment]
ping @Constellation

**Comment by nzakas** [comment]
@nre why don't you put together a PR so we can see how complex of a change it is? Sometimes code is a better argument. :)
